# Generated by Django 4.1.4 on 2025-06-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer', '0002_alter_useraccount_name_alter_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0),
        ),
    ]
