# Generated by Django 4.1.4 on 2025-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer', '0003_useraccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='session_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
