# Generated by Django 5.2.3 on 2025-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer', '0006_product_is_scheduled_product_status_productschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
