# Generated by Django 5.2.3 on 2025-07-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer', '0007_product_variant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
        migrations.AddField(
            model_name='product',
            name='regions',
            field=models.ManyToManyField(related_name='products', to='razer.region'),
        ),
    ]
