# Generated by Django 5.2.3 on 2025-07-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razer', '0008_remove_product_region_product_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_account',
        ),
    ]
