# Generated by Django 5.2.3 on 2025-07-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer', '0010_remove_product_quantity_remove_product_regions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
